server:
  port: 8182
  servlet.context-path: /toutiao

##### spring #####
spring:
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.18.14.121:3306/cloud_toutiao?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: Jyzh@123
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

dubbo:
  application:
    id: toutiao
    name: toutiao
    qos-port: 40000
  service:
      version: 1.0.0
  protocol:
    id: dubbo
    name: dubbo
    port: 30000
  registry:
    id: my-registry
    address: zookeeper://172.18.14.121:2181
user:
  service:
    version: 1.0.0
    url: dubbo://172.18.14.121:10000

#人脸卡口区域字典code
alarm:
  regionCode: 2f006d1fe0834a269cf97fd7129f200f